### ISSUE TITLE
sse/static/js/main.js contains git merge artifacts

### ISSUE THREAD

**Issue by jmz-b** [UoW-CPC/Asclepios-Client#2]
So I've just spent some time exploring this code base, and I've noticed that `sse/static/js/main.js` contains some git merge artifacts, for example:

```
2  var appConfig={
3  <<<<<<< HEAD
```

and 

```
195  function handleFileLoad(event){
196  >>>>>>> develop
```

and there are some more.

It looks like `develop` was merged into `master` and some merge conflicts were never resolved before pushing.

Now I haven't actually got to the point where I am testing the client yet, but I have to assume this is going to break things.

Regards,
James

**Comment by jmz-b** [comment]
So I have got to testing the client and it appears that yes, this does break things.

The console shows an error on one of the merge artifact lines, and the "input by form" button does nothing, see attached screenshot

![Screenshot from 2020-03-25 16-20-55](https://user-images.githubusercontent.com/9866884/77553224-d2eae700-6eb4-11ea-8b73-a77ee49058ea.png)

**Comment by hvandang** [comment]
Thanks, James. It is resolved now.
